#!/bin/bash
DIR=$(dirname "$0")
cd $DIR
clear

PATH=$DIR/build/arm64:$PATH

pxfnt assets/BBC.bmp -o assets/fonts/BBC.h -f 32 -l 255 -w 8 -h 16 -y 16 -H 8 -F -u 0
pxfnt assets/VGA.pbm -o assets/fonts/VGA.h -f 0 -l 255 -w 9 -h 16 -F -u 0 -s 9
pxfnt assets/EGA.pbm -o assets/fonts/EGA.h -f 0 -l 255 -w 8 -h 14 -V 2 -F -u 0 -s 8
pxfnt assets/ARCADE.pbm -o assets/fonts/ARCADE.h -f 32 -l 140 -w 8 -h 8 -F -u 0
pxfnt assets/HD44780.bmp -o assets/fonts/HD44780.h -f 32 -l 255 -w 5 -h 10 -F -i 3 -g v -H 1 -V 1 -x 1 -y 1
pxfnt assets/CGA.pbm -o assets/fonts/CGA.h -f 0 -l 255 -w 8 -h 8 -F -u 0 -s 8

pxfnt assets/fonts/BBC.h -o assets/fonts/BBC.hpprgm
pxfnt assets/fonts/VGA.h -o assets/fonts/VGA.hpprgm
pxfnt assets/fonts/EGA.h -o assets/fonts/EGA.hpprgm
pxfnt assets/fonts/ARCADE.h -o assets/fonts/ARCADE.hpprgm
pxfnt assets/fonts/HD44780.h -o assets/fonts/HD44780.hpprgm
pxfnt assets/fonts/CGA.h -o assets/fonts/CGA.hpprgm

pxfnt assets/fonts/BBC.hpprgm -o assets/fonts/BBC.bmp -c 128
pxfnt assets/fonts/VGA.hpprgm -o assets/fonts/VGA.bmp -c 128
pxfnt assets/fonts/EGA.hpprgm -o assets/fonts/EGA.bmp -c 128
pxfnt assets/fonts/ARCADE.hpprgm -o assets/fonts/ARCADE.bmp -c 128
pxfnt assets/fonts/HD44780.hpprgm -o assets/fonts/HD44780.bmp -g v -c 14
pxfnt assets/fonts/CGA.hpprgm -o assets/fonts/CGA.bmp -c 128


read -p "DONE! Press Enter to close window."

# Close the Terminal window
osascript -e 'tell application "Terminal" to close window 1' & exit
