#!/bin/bash
DIR=$(dirname "$0")
printf '\e[1;40;92m'
clear

cd $DIR

# Use find to locate the .xcodeproj file
xcodeproj_file=$(find . -name "*.xcodeproj" -print -quit)

# Check if a .xcodeproj file was found
if [ -n "$xcodeproj_file" ]; then
    xcodeproj_name=$(basename "$xcodeproj_file" .xcodeproj)
else
    echo "No .xcodeproj file found."
    # Close the Terminal window
    osascript -e 'tell application "Terminal" to close window 1' & exit
fi

echo "WWW"

www=/usr/local/var/www
cp macos.zip $www/downloads/macos/$xcodeproj_name.zip
cp linux.zip $www/downloads/linux/$xcodeproj_name.zip
cp windows.zip $www/downloads/pc/$xcodeproj_name.zip

# Ask the user a question
result=$(osascript -e 'display dialog "Do you want upload the build info?" buttons {"Yes", "No"} default button "Yes"')

# Process the result
if [[ "$result" == *"Yes"* ]]; then
    cp src/build.txt $www/downloads/$xcodeproj_name.txt
fi


# Close the Terminal window
osascript -e 'tell application "Terminal" to close window 1' & exit
