#!/bin/bash
DIR=$(dirname "$0")
cd $DIR
clear

PATH=$DIR/../../build/arm64:$PATH

ASSETS=assets/CASIO
FONTS=../fonts/CASIO
NAME=fxCG50_24pt

pxfnt $NAME.pbm -o $FONTS/${NAME}0xXX.h -f 0 -l 255 -w 18 -h 24 -F -u 0
pxfnt $FONTS/${NAME}0xXX.h -o $FONTS/${NAME}0xXX.hpprgm
pxfnt $FONTS/${NAME}0xXX.hpprgm -o $FONTS/${NAME}0xXX.bmp -c 64

pxfnt $NAME.pbm -o $FONTS/${NAME}0x7FXX.h -f 0 -l 255 -w 18 -h 24 -F -u 0 -y 48
pxfnt $FONTS/${NAME}0x7FXX.h -o $FONTS/${NAME}0x7FXX.hpprgm
pxfnt $FONTS/${NAME}0x7FXX.hpprgm -o $FONTS/${NAME}0x7FXX.bmp -c 64

pxfnt $NAME.pbm -o $FONTS/${NAME}0xE5XX.h -f 0 -l 255 -w 18 -h 24 -F -u 0 -y 96
pxfnt $FONTS/${NAME}0xE5XX.h -o $FONTS/${NAME}0xE5XX.hpprgm
pxfnt $FONTS/${NAME}0xE5XX.hpprgm -o $FONTS/${NAME}0xE5XX.bmp -c 64

pxfnt $NAME.pbm -o $FONTS/${NAME}0xE6XX.h -f 0 -l 255 -w 18 -h 24 -F -u 0 -y 144
pxfnt $FONTS/${NAME}0xE6XX.h -o $FONTS/${NAME}0xE6XX.hpprgm
pxfnt $FONTS/${NAME}0xE6XX.hpprgm -o $FONTS/${NAME}0xE6XX.bmp -c 64


read -p "DONE! Press Enter to close window."

# Close the Terminal window
osascript -e 'tell application "Terminal" to close window 1' & exit
