// Generated by Insoft Adafruit GFX Pixel Font Creator version, 1.1.0
// Copyright (C) 2024-2025 Insoft. All rights reserved.

#ifndef PROGMEM
    #define PROGMEM /* None Arduino */
#endif

#ifndef HD44780_h
#define HD44780_h

const unsigned char HD44780_Bitmaps[] PROGMEM = {
    
};

const GFXglyph HD44780_Glyphs[] PROGMEM = {
    {     0,   0,   0,   6,   0,   0 }   // 0x20 ' '
};

const GFXfont HD44780 PROGMEM = {
    (unsigned char *) HD44780_Bitmaps, 
    (GFXglyph *) HD44780_Glyphs, 
    32, 
    32, 
    10
};

#endif /* HD44780_h */
