#!/bin/bash
DIR=$(dirname "$0")
clear
cd $DIR

#!/bin/bash

pkgbuild --root package-root \
         --identifier uk.insoft.pixfont \
         --version 1.0 --install-location / \
         --scripts scripts \
         pxfnt.pkg
         
IDENTITY=$(security find-identity -v -p basic | grep "Developer ID Installer" | awk '{print $2}')
productsign --sign "$IDENTITY" pxfnt.pkg piXfont.pkg

rm -rf pxfnt.pkg
 

read -p "Press Enter to exit!"

# Close the Terminal window
osascript -e 'tell application "Terminal" to close window 1' & exit
